import React from 'react';
import { MapPin, Navigation, Phone, CalendarRange, Clock } from 'lucide-react';

export default function Location({ onOpenBookModal }) {
  const address = "1/74, State Highway 49, Muthukadu, Tamil Nadu 603112";
  const mapsSearchUrl = `https://www.google.com/maps/search/?api=1&query=Geetham+Veg+Restaurant+Muttukadu`;
  return (
    <section id="location" className="py-24 px-4 sm:px-6 lg:px-8 bg-brand-cream dark:bg-[#061d12] theme-transition select-none">
      <div className="max-w-7xl mx-auto">
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 lg:gap-16 items-center">
          <div className="lg:col-span-5 flex flex-col justify-center"><span className="text-xs sm:text-sm font-bold tracking-[0.2em] text-[#D95A1E] uppercase mb-4 block">FIND US</span><h2 className="font-serif text-3xl sm:text-4xl lg:text-[2.75rem] font-normal tracking-tight text-brand-charcoal dark:text-brand-cream-ivory leading-[1.1] mb-8">Right on ECR, <br />in the heart of <br />Muttukadu.</h2><div className="space-y-6 mb-8"><div className="flex gap-4 items-start"><MapPin className="w-5 h-5 text-[#D95A1E] shrink-0 mt-0.5" /><span className="text-[15px] font-medium text-brand-charcoal/80 dark:text-brand-cream-ivory/80 leading-relaxed">{address}</span></div><div className="flex gap-4 items-center"><Phone className="w-5 h-5 text-[#D95A1E] shrink-0" /><a href="tel:07904058228" className="text-[15px] font-medium text-brand-charcoal/80 dark:text-brand-cream-ivory/80 hover:text-[#D95A1E] transition-colors">079040 58228</a></div><div className="flex gap-4 items-center"><Clock className="w-5 h-5 text-[#D95A1E] shrink-0" /><span className="text-[15px] font-medium text-brand-charcoal/80 dark:text-brand-cream-ivory/80">Open until 12 AM · Daily</span></div></div><div className="space-y-3"><div className="flex flex-col sm:flex-row gap-3"><a href={mapsSearchUrl} target="_blank" rel="noopener noreferrer" className="flex-1 py-3 px-6 rounded-full bg-[#D95A1E] hover:bg-brand-saffron-dark text-white font-semibold flex items-center justify-center gap-2 shadow-md transition-all duration-300 hover:scale-[1.02]"><Navigation className="w-4 h-4 fill-white rotate-45 shrink-0" /><span>Get Directions</span></a><a href="tel:07904058228" className="flex-1 py-3 px-6 rounded-full border border-brand-charcoal/20 dark:border-white/20 hover:bg-brand-charcoal/5 dark:hover:bg-white/5 text-brand-charcoal dark:text-white font-semibold flex items-center justify-center gap-2 transition-all duration-300 hover:scale-[1.02]"><Phone className="w-4 h-4 text-brand-gold shrink-0" /><span>Call Now</span></a></div><button onClick={onOpenBookModal} className="w-full sm:w-auto py-3 px-8 rounded-full border border-brand-charcoal/20 dark:border-white/20 hover:bg-brand-charcoal/5 dark:hover:bg-white/5 text-brand-charcoal dark:text-white font-semibold flex items-center justify-center gap-2 transition-all duration-300 hover:scale-[1.02]"><CalendarRange className="w-4 h-4 text-brand-gold shrink-0" /><span>Reserve Table</span></button></div></div>
          <div className="lg:col-span-7 aspect-[4/3] rounded-[28px] overflow-hidden border border-brand-gold/15 shadow-xl relative min-h-[350px] sm:min-h-[450px]"><iframe title="Geetham Muttukadu Google Maps Location" src="https://maps.google.com/maps?q=Geetham%20Veg%20Restaurant%20-%20Muttukadu,%201/74,%20State%20Highway%2049,%20Muthukadu,%20Tamil%20Nadu%20603112&t=&z=15&ie=UTF8&iwloc=&output=embed" className="absolute inset-0 w-full h-full border-none grayscale-[5%] contrast-[105%] opacity-95 dark:opacity-80 dark:invert-[90%] dark:hue-rotate-[180deg]" allowFullScreen="" loading="lazy" referrerPolicy="no-referrer-when-downgrade" /></div>
        </div>
      </div>
    </section>
  );
}
