import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Plus } from 'lucide-react';

export default function MenuPreview({ onAddToCart }) {
  const [activeCategory, setActiveCategory] = useState('Breakfast');
  const menuCategories = ['Breakfast', 'South Indian Meals', 'Beverages', 'Desserts'];
  const menuData = { 'Breakfast': [{ name: "Steamed Idli (2 Pcs)", price: "₹90", tag: "Classic" }, { name: "Ghee Podi Masala Dosa", price: "₹190", tag: "Signature" }, { name: "Medu Vada (2 Pcs)", price: "₹90" }, { name: "Rava Khichdi", price: "₹100" }, { name: "Ghee Roast Dosa", price: "₹160", tag: "Popular" }], 'South Indian Meals': [{ name: "Geetham Special Thali", price: "₹260", tag: "Signature Feast" }, { name: "ECR Mini Lunch", price: "₹160", tag: "Popular" }, { name: "Sambar Sadham", price: "₹120" }, { name: "Curd Rice", price: "₹110" }], 'Beverages': [{ name: "Filter Coffee", price: "₹70", tag: "Legendary" }, { name: "Buttermilk", price: "₹50" }, { name: "Badam Milk", price: "₹110" }, { name: "Masala Chai", price: "₹60" }, { name: "Fresh Lime Soda", price: "₹80" }], 'Desserts': [{ name: "Royal Falooda", price: "₹180", tag: "Popular" }, { name: "Elaneer Payasam", price: "₹130", tag: "Must Try" }, { name: "Gulab Jamun with Ice Cream", price: "₹120" }] };
  return (
    <section id="menu" className="py-24 px-4 sm:px-6 lg:px-8 bg-brand-cream dark:bg-[#061d12] theme-transition select-none">
      <div className="max-w-6xl mx-auto">
        <div className="text-left mb-10 max-w-2xl"><span className="text-xs sm:text-sm font-bold tracking-[0.2em] text-[#D95A1E] uppercase mb-3 block">MENU PREVIEW</span><h2 className="font-serif text-3xl sm:text-4xl lg:text-[2.5rem] font-normal tracking-tight text-brand-charcoal dark:text-brand-cream-ivory leading-[1.15] mb-4">From breakfast idli to midnight <br />ghee dosa.</h2><p className="text-sm sm:text-base text-brand-charcoal/80 dark:text-brand-cream-ivory/80 leading-relaxed font-medium">A curated peek into our most loved sections. Full menu served in-restaurant.</p></div>
        <div className="flex justify-start mb-16 overflow-x-auto no-scrollbar py-2"><div className="flex gap-2 bg-brand-cream-surface dark:bg-[#0c2419] p-1.5 rounded-full border border-brand-gold/10 relative">{menuCategories.map(category => { const isActive = activeCategory === category; return (<button key={category} onClick={() => setActiveCategory(category)} className={`relative px-6 py-2.5 rounded-full text-sm font-semibold tracking-wide transition-all duration-300 whitespace-nowrap cursor-pointer z-10 ${isActive ? 'text-white' : 'text-brand-charcoal/80 dark:text-brand-cream-ivory/80 hover:text-brand-saffron dark:hover:text-brand-saffron'}`}>{isActive && (<motion.div layoutId="activeMenuTab" className="absolute inset-0 bg-[#D95A1E] rounded-full -z-10 shadow-md" transition={{ type: "spring", stiffness: 380, damping: 30 }} />)}{category}</button>); })}</div></div>
        <div className="max-w-5xl min-h-[300px]"><AnimatePresence mode="wait"><motion.div key={activeCategory} initial={{ opacity: 0, y: 15 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -15 }} transition={{ duration: 0.3 }} className="grid grid-cols-1 md:grid-cols-2 gap-x-12 gap-y-6">{menuData[activeCategory].map((item, idx) => (<div key={item.name} className="flex items-center justify-between p-4 -mx-4 rounded-[16px] hover:bg-brand-cream-surface/65 dark:hover:bg-[#0c2419]/65 border border-transparent hover:border-brand-gold/15 transition-all duration-300 group"><span className="font-serif text-lg sm:text-xl font-normal text-brand-charcoal dark:text-brand-cream-ivory group-hover:text-brand-saffron dark:group-hover:text-brand-gold transition-colors duration-300 flex items-center gap-2.5"><span>{item.name}</span>{item.tag && (<span className="text-[9px] font-bold tracking-wider uppercase px-2 py-0.5 rounded-full bg-brand-saffron/10 dark:bg-brand-saffron/20 text-[#D95A1E] dark:text-[#ff8e53] border border-brand-saffron/20 shrink-0 select-none">{item.tag}</span>)}</span><div className="flex-1 mx-4 border-b border-dotted border-brand-gold/25 dark:border-brand-gold/15 group-hover:border-brand-saffron/35 dark:group-hover:border-brand-gold/35 transition-colors duration-300" /><div className="flex items-center gap-3.5 shrink-0"><span className="font-serif text-lg sm:text-xl font-normal text-[#D95A1E] dark:text-brand-saffron-light group-hover:scale-105 transition-all duration-300">{item.price}</span>{onAddToCart && (<motion.button whileTap={{ scale: 0.95 }} whileHover={{ scale: 1.1 }} onClick={() => onAddToCart(item)} className="w-8 h-8 rounded-full border border-brand-gold/30 hover:border-brand-saffron hover:bg-brand-saffron dark:hover:bg-brand-gold hover:text-white dark:hover:text-[#061d12] text-brand-gold dark:text-brand-gold flex items-center justify-center transition-all duration-300 cursor-pointer shadow-sm" title="Add to Gourmet Cart"><Plus className="w-4 h-4" /></motion.button>)}</div></div>))}</motion.div></AnimatePresence></div>
      </div>
    </section>
  );
}
