import React from 'react';
import { motion } from 'framer-motion';
import { Star } from 'lucide-react';

export default function Reviews() {
  const testimonials = [ { quote: "ECR best place to eat and best parking and good service food good.", author: "Karthik R.", label: "CHENNAI" }, { quote: "Food taste, quality, quantity, service standards, ambience are all awesome.", author: "Priya S.", label: "ECR REGULAR" }, { quote: "Ambient space, good space for car park... food items very tasty.", author: "Rajesh M.", label: "VISITED WITH FAMILY" } ];
  return (
    <section id="reviews" className="py-24 px-4 sm:px-6 lg:px-8 bg-brand-cream dark:bg-[#061d12] theme-transition select-none"><div className="max-w-7xl mx-auto"><div className="text-center mb-16"><span className="text-xs sm:text-sm font-bold tracking-[0.25em] text-brand-saffron uppercase mb-3 block">GUEST STORIES</span><h2 className="font-serif text-3xl sm:text-4xl lg:text-[2.5rem] font-bold tracking-tight text-brand-charcoal dark:text-brand-cream-ivory">Why guests rate us <span className="text-brand-saffron font-serif font-semibold">3.9★</span> across <br className="hidden sm:block" /> 11,962 visits.</h2></div><div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">{testimonials.map((item, index) => (<motion.div key={item.author} initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: "-100px" }} transition={{ duration: 0.7, delay: index * 0.15, ease: 'easeOut' }} whileHover={{ scale: 1.02 }} className="p-8 rounded-[24px] bg-brand-cream-surface dark:bg-[#0c2419] border border-brand-gold/15 dark:border-brand-gold/10 hover:border-brand-gold/25 shadow-lg relative flex flex-col justify-between h-full group transition-all duration-500"> <div><div className="font-serif text-6xl text-brand-gold/70 leading-[0.3] mb-4 select-none">“</div><div className="flex gap-1 mb-5">{[...Array(5)].map((_, i) => (<Star key={i} className={`w-4 h-4 ${i < 4 ? 'fill-brand-gold stroke-brand-gold' : 'fill-brand-gold/20 stroke-brand-gold/25'}`} />))}</div><blockquote className="text-brand-charcoal dark:text-brand-cream-ivory/90 text-[15px] sm:text-base leading-relaxed italic mb-8 font-sans transition-colors duration-300">"{item.quote}"</blockquote></div><div><div className="w-full h-px bg-brand-gold/15 dark:bg-brand-gold/10 group-hover:bg-brand-gold/25 transition-colors mb-5 duration-500" /><div><cite className="not-italic font-bold text-brand-charcoal dark:text-white tracking-wide block mb-1 transition-colors duration-300">{item.author}</cite><span className="text-[10px] sm:text-xs font-bold tracking-widest text-brand-charcoal/60 dark:text-brand-cream-ivory/50 uppercase block transition-colors duration-300">{item.label}</span></div></div></motion.div>))}</div></div></section>
  );
}
